// Autogenerated AST node
package org.kamalyes.jython3.antlr.ast;

import org.kamalyes.jython3.antlr.AST;

public enum cmpopType {
  UNDEFINED,
  Eq,
  NotEq,
  Lt,
  LtE,
  Gt,
  GtE,
  Is,
  IsNot,
  In,
  NotIn;
}
