// Autogenerated AST node
package org.kamalyes.jython3.antlr.ast;

import org.kamalyes.jython3.antlr.AST;

public enum expr_contextType {
  UNDEFINED,
  Load,
  Store,
  Del,
  AugLoad,
  AugStore,
  Param;
}
