// Autogenerated AST node
package org.kamalyes.jython3.antlr.ast;

import org.antlr.runtime.Token;
import org.kamalyes.jython3.antlr.PythonTree;
import org.kamalyes.jython3.antlr.adapter.AstAdapters;
import org.kamalyes.jython3.antlr.base.expr;
import org.kamalyes.jython3.antlr.base.mod;
import org.kamalyes.jython3.core.ArgParser;
import org.kamalyes.jython3.core.Py;
import org.kamalyes.jython3.core.PyObject;
import org.kamalyes.jython3.core.PyUnicode;
import org.kamalyes.jython3.core.PyStringMap;
import org.kamalyes.jython3.core.PyType;
import org.kamalyes.jython3.expose.ExposedGet;
import org.kamalyes.jython3.expose.ExposedMethod;
import org.kamalyes.jython3.expose.ExposedNew;
import org.kamalyes.jython3.expose.ExposedSet;
import org.kamalyes.jython3.expose.ExposedType;

@ExposedType(name = "_ast.Expression", base = mod.class)
public class Expression extends mod {
  public static final PyType TYPE = PyType.fromClass(Expression.class);
  private expr body;

  public expr getInternalBody() {
    return body;
  }

  @ExposedGet(name = "body")
  public PyObject getBody() {
    return body;
  }

  @ExposedSet(name = "body")
  public void setBody(PyObject body) {
    this.body = AstAdapters.py2expr(body);
  }

  private final static PyUnicode[] fields = new PyUnicode[] { new PyUnicode("body") };

  @ExposedGet(name = "_fields")
  public PyUnicode[] get_fields() {
    return fields;
  }

  private final static PyUnicode[] attributes = new PyUnicode[0];

  @ExposedGet(name = "_attributes")
  public PyUnicode[] get_attributes() {
    return attributes;
  }

  public Expression(PyType subType) {
    super(subType);
  }

  public Expression() {
    this(TYPE);
  }

  @ExposedNew
  @ExposedMethod
  public void Expression___init__(PyObject[] args, String[] keywords) {
    ArgParser ap = new ArgParser("Expression", args, keywords, new String[] { "body" }, 1, true);
    setBody(ap.getPyObject(0, Py.None));
  }

  public Expression(PyObject body) {
    setBody(body);
  }

  public Expression(Token token, expr body) {
    super(token);
    this.body = body;
    addChild(body);
  }

  public Expression(Integer ttype, Token token, expr body) {
    super(ttype, token);
    this.body = body;
    addChild(body);
  }

  public Expression(PythonTree tree, expr body) {
    super(tree);
    this.body = body;
    addChild(body);
  }

  @ExposedGet(name = "repr")
  public String toString() {
    return "Expression";
  }

  public String toStringTree() {
    StringBuffer sb = new StringBuffer("Expression(");
    sb.append("body=");
    sb.append(dumpThis(body));
    sb.append(",");
    sb.append(")");
    return sb.toString();
  }

  public <R> R accept(VisitorIF<R> visitor) throws Exception {
    return visitor.visitExpression(this);
  }

  public void traverse(VisitorIF<?> visitor) throws Exception {
    if (body != null)
      body.accept(visitor);
  }

  public PyObject __dict__;

  @Override
  public PyObject fastGetDict() {
    ensureDict();
    return __dict__;
  }

  @ExposedGet(name = "__dict__")
  public PyObject getDict() {
    return fastGetDict();
  }

  private void ensureDict() {
    if (__dict__ == null) {
      __dict__ = new PyStringMap();
    }
  }

}
