// Autogenerated AST node
package org.kamalyes.jython3.antlr.ast;

import org.kamalyes.jython3.antlr.AST;

public enum operatorType {
  UNDEFINED,
  Add,
  Sub,
  Mult,
  MatMult,
  Div,
  Mod,
  Pow,
  LShift,
  RShift,
  BitOr,
  BitXor,
  BitAnd,
  FloorDiv;
}
